/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fattore.h"

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 12))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Gudge (XDR *xdrs, Gudge *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giudici, NGUDGES,
		sizeof (Gudge), (xdrproc_t) xdr_Gudge))
		 return FALSE;
	return TRUE;
}
