/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FATTORE_H_RPCGEN
#define _FATTORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NGUDGES 4

struct Input {
	char *name;
	char *operation;
};
typedef struct Input Input;

struct Gudge {
	char *name;
};
typedef struct Gudge Gudge;

struct Output {
	Gudge giudici[NGUDGES];
};
typedef struct Output Output;

#define FATTORE 0x20000013
#define FATTOREVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define vote 1
extern  int * vote_1(Input *, CLIENT *);
extern  int * vote_1_svc(Input *, struct svc_req *);
#define gudges_rank 2
extern  Output * gudges_rank_1(void *, CLIENT *);
extern  Output * gudges_rank_1_svc(void *, struct svc_req *);
extern int fattore_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define vote 1
extern  int * vote_1();
extern  int * vote_1_svc();
#define gudges_rank 2
extern  Output * gudges_rank_1();
extern  Output * gudges_rank_1_svc();
extern int fattore_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Gudge (XDR *, Gudge*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Gudge ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FATTORE_H_RPCGEN */
