/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operazioni.h"

bool_t
xdr_infoFile (XDR *xdrs, infoFile *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->nChar))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nWord))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nLine))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_dir (XDR *xdrs, req_dir *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nomeDir, MAXLENGTH))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->limit))
		 return FALSE;
	return TRUE;
}
