/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERAZIONI_H_RPCGEN
#define _OPERAZIONI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLENGTH 256

struct infoFile {
	int nChar;
	int nWord;
	int nLine;
};
typedef struct infoFile infoFile;

struct req_dir {
	char *nomeDir;
	int limit;
};
typedef struct req_dir req_dir;

#define OPFILEPROGRAM 0x20000001
#define OPFILEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define file_scan 1
extern  infoFile * file_scan_1(char **, CLIENT *);
extern  infoFile * file_scan_1_svc(char **, struct svc_req *);
#define dir_scan 2
extern  int * dir_scan_1(req_dir *, CLIENT *);
extern  int * dir_scan_1_svc(req_dir *, struct svc_req *);
extern int opfileprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define file_scan 1
extern  infoFile * file_scan_1();
extern  infoFile * file_scan_1_svc();
#define dir_scan 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int opfileprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_infoFile (XDR *, infoFile*);
extern  bool_t xdr_req_dir (XDR *, req_dir*);

#else /* K&R C */
extern bool_t xdr_infoFile ();
extern bool_t xdr_req_dir ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERAZIONI_H_RPCGEN */
